config/routes.rb
Startupality::Application.routes.draw do
  root :to => 'angular#angular'
  match 'angular/angular' => 'angular#angular'

  resources :projects do
    collection do
      get 'getActivated'
    end
  end

  devise_for :users
  resources :users do
  end
  resources :userutil do
    post :fetch_current_user,:on=>:collection
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
        if user.role == "partner" or user.role == "admin" or user.role == "normal-user"
             can :manage, :all
        else
            #can :view, Script do |script|
            #    script.user_id==user.id
            #end
            can :edit, Script do |script|
                script.user_id==user.id
            end
            can :delete, Script do |script|
                script.user_id==user.id
            end
            can :view,:all
            can :review,:all 
        end
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :activated, :title
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	ROLES = %w[partner admin normal-user premium-user]
	# Include default devise modules. Others available are:
	# :token_authenticatable, :confirmable,
	# :lockable, :timeoutable and :omniauthable
  has_many :projects, :dependent => :destroy
	devise :database_authenticatable, :registerable,
				 :recoverable, :rememberable, :trackable, :validatable

	# Setup accessible (or protected) attributes for your model
	attr_accessible :email, :password, :password_confirmation, :role,:remember_me
	validates :email, :presence => true, :uniqueness => true,
                      :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}
	before_validation :downcase_email
		def downcase_email
			self.email = self.email.downcase if self.email.present?
    end
  after_create :default_role

  def default_role
    self.role = "normal-user"
    self.save
  end
	# attr_accessible :title, :body
end

app/controllers/angular_controller.rb
class AngularController < ApplicationController
  def angular
    respond_to do |format|
      format.html
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    #@projects = Project.all
    @projects = Project.where(:user_id => current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  #def new
  #  # NOT USED, LOOK FOR CREATE
  #  @project = Project.new
  #  @project.user_id = current_user.id;
  #
  #  respond_to do |format|
  #    format.html # new.html.erb
  #    format.json { render json: @project }
  #  end
  #end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    # Save for current user
    @project.user_id = current_user.id;

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])
    # user_id should stay the same

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  # Get Currently active project
  def getActivated
    @project = Project.where("activated = true").where(:user_id => current_user.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end
end

app/controllers/userutil_controller.rb
class UserutilController < ApplicationController
	respond_to :html, :xml, :js, :json
	before_filter :authenticate_user!
	skip_before_filter :verify_authenticity_token

	def fetch_current_user
		#current_user.slice(:id,:role)
		render :json => current_user
	end

	def index
	User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_div(kind)
		unless flash[kind].blank?
			text = "<p>#{flash[kind]}</p>"
			content_tag :div, text.html_safe, :id => "flash", :class => kind
		end
	end
	def current_navigation expected_path
		if params[:controller] ==expected_path
			return "active"
		else
			return ""
		end
	end
end

app/views/angular/angular.html.erb
<div class="container" ng-app="mainapp">
    <div ng-include src="'<%= asset_path('partials/header.html') %>'">
    </div>
    <div id="main" ng-view></div>
    <div ng-include src="'<%= asset_path('partials/footer.html') %>'">
    </div>
</div>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MyApp
    %meta{'charset' => "utf-8"}
    %meta{'http-equiv' => "X-UA-Compatible", 'content' => "IE=edge,chrome=1"}
    %meta{'name' => "viewport", :content => "width=device-width, initial-scale=1"}
    %meta{'content' => "text/html; charset=UTF-8", 'http-equiv' => "Content-Type"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    <!--[if lte IE 8]><script src="assets/lib/angular-ui-ieshiv.js"></script><![endif]-->
    = csrf_meta_tags
    = yield :header
  %body{:id => "%s_%s" % [controller_name, action_name]}
    / = render "layouts/header"
    = yield
    = yield :footer

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :completed %><br />
    <%= f.check_box :completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Completed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.title %></td>
    <td><%= project.completed %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @project.title %>
</p>

<p>
  <b>Completed:</b>
  <%= @project.completed %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>